# Generated by Django 4.2.25 on 2025-11-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huecos', '0004_comentario_created_at_comentario_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hueco',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='huecos/'),
        ),
    ]
