# Generated by Django 4.2.25 on 2025-12-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huecos', '0005_hueco_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='hueco',
            name='imagen_preview',
            field=models.ImageField(blank=True, null=True, upload_to='huecos/preview/'),
        ),
    ]
