# Generated by Django 4.2.25 on 2025-11-05 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huecos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hueco',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='hueco',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='hueco',
            name='verificado',
        ),
        migrations.AddField(
            model_name='hueco',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hueco',
            name='numero_ciclos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hueco',
            name='validaciones_negativas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hueco',
            name='validaciones_positivas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hueco',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hueco',
            name='estado',
            field=models.CharField(choices=[('pendiente_validacion', 'Pendiente de validación'), ('activo', 'Activo'), ('rechazado', 'Rechazado'), ('reabierto', 'Reabierto'), ('cerrado', 'Cerrado')], default='pendiente_validacion', max_length=30),
        ),
        migrations.AlterField(
            model_name='hueco',
            name='latitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hueco',
            name='longitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hueco',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huecos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='puntosusuario',
            name='tipo',
            field=models.CharField(choices=[('reporte', 'Reporte creado'), ('verificacion', 'Reporte verificado'), ('confirmacion', 'Confirmación de estado'), ('comentario', 'Comentario o interacción'), ('reporte_falso', 'Reporte falso o rechazado'), ('admin', 'Ajuste manual')], max_length=50),
        ),
        migrations.CreateModel(
            name='ValidacionHueco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.BooleanField(help_text='True = confirma que el hueco existe, False = no existe')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hueco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='huecos.hueco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hueco', 'usuario')},
            },
        ),
    ]
