# Generated by Django 4.2.25 on 2025-11-09 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huecos', '0002_remove_hueco_direccion_remove_hueco_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_fcm', models.CharField(max_length=255, unique=True)),
                ('plataforma', models.CharField(default='android', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
