# Generated by Django 4.2.25 on 2025-12-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huecos', '0006_hueco_imagen_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='hueco',
            name='gravedad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='hueco',
            name='vistas',
            field=models.IntegerField(default=0),
        ),
    ]
