# Generated by Django 4.2.25 on 2025-12-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huecos', '0007_hueco_gravedad_hueco_vistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacion',
            name='nuevo_estado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='confirmado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hueco',
            name='estado',
            field=models.CharField(choices=[('pendiente_validacion', 'Pendiente de validación'), ('activo', 'Activo'), ('rechazado', 'Rechazado'), ('reabierto', 'Reabierto'), ('cerrado', 'Cerrado'), ('en_reparacion', 'En reparación'), ('reparado', 'Reparado')], default='pendiente_validacion', max_length=30),
        ),
    ]
