# Generated by Django 4.2.25 on 2025-12-31 23:35

from django.db import migrations, models


def convert_states_to_int(apps, schema_editor):
    Hueco = apps.get_model('huecos', 'Hueco')
    Confirmacion = apps.get_model('huecos', 'Confirmacion')

    mapping = {
        'pendiente_validacion': 1,
        'activo': 2,
        'rechazado': 3,
        'reabierto': 4,
        'cerrado': 5,
        'en_reparacion': 6,
        'reparado': 7,
    }

    # Convertir Hueco.estado
    for h in Hueco.objects.all():
        # Si ya es digito, lo dejamos (por si acaso se corre parcial)
        if str(h.estado).isdigit():
            continue
        val = mapping.get(h.estado, 1) # Default to 1 if unknown
        h.estado = str(val) # Guardamos como string "2" para que luego se castee a int
        h.save()

    # Convertir Confirmacion.nuevo_estado
    for c in Confirmacion.objects.all():
        if c.nuevo_estado and not str(c.nuevo_estado).isdigit():
            val = mapping.get(c.nuevo_estado, 1)
            c.nuevo_estado = str(val)
            c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('huecos', '0008_confirmacion_nuevo_estado_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_states_to_int),
        migrations.RemoveField(
            model_name='confirmacion',
            name='confirmado',
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='nuevo_estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pendiente de validación'), (2, 'Activo'), (3, 'Rechazado'), (4, 'Reabierto'), (5, 'Cerrado'), (6, 'En reparación'), (7, 'Reparado')], default=1),
        ),
        migrations.AlterField(
            model_name='hueco',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pendiente de validación'), (2, 'Activo'), (3, 'Rechazado'), (4, 'Reabierto'), (5, 'Cerrado'), (6, 'En reparación'), (7, 'Reparado')], default=1),
        ),
    ]
