# Generated by Django 4.2.25 on 2025-12-31 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huecos', '0009_remove_confirmacion_confirmado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='confirmacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='numero_ciclo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='confirmacion',
            unique_together={('hueco', 'usuario', 'numero_ciclo')},
        ),
    ]
