# Generated by Django 4.2.25 on 2026-03-12 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huecos', '0010_alter_confirmacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hueco',
            name='denuncias_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DenunciaHueco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('motivo', models.CharField(choices=[('obscene', 'Imagen Obscena/Inapropiada'), ('spam', 'Spam / Falso'), ('offensive', 'Lenguaje Ofensivo'), ('other', 'Otro')], default='other', max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('hueco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='huecos.hueco')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hueco', 'usuario')},
            },
        ),
    ]
