# Generated by Django 4.2.25 on 2025-11-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_reputacionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google'), ('facebook', 'Facebook'), ('mixed', 'Google + Email')], default='email', max_length=20),
        ),
    ]
