# Generated by Django 4.2.25 on 2025-11-05 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_user_created_by_alter_user_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.IntegerField(default=0)),
                ('nivel_confianza', models.CharField(default='nuevo', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
